name: Build and Test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        step: ['format:check', 'lint:check']
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn ${{ matrix.step }}
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn build
      - run: yarn test
